Modernize Meson usage
bil-elmoussaoui/nautilus-git pull request #24
Opened 2017-06-02 17:19 UTC by TingPing

2017-06-02 17:52 UTC, bil-elmoussaoui commented
Awesome thanks for the great work ! :+1:  Just wonder as the pot file doesn't exists anymore, how anyone can translate the extension ? 
+ The POTFILES doesn't contain all the files that have a trasnlatable string on theme, there's also the nemo-git/git.py.in

2017-06-02 18:00 UTC, TingPing commented
> Awesome thanks for the great work ! :+1: Just wonder as the pot file doesn't exists anymore, how anyone can translate the extension ?

You can generate the file with `ninja nautilus-git-pot`, also `ninja nautilus-git-update-po`.

> The POTFILES doesn't contain all the files that have a trasnlatable string on theme, there's also the nemo-git/git.py.in

Thanks, will add.

2017-06-02 18:20 UTC, bilelmoussaoui requested changes

2017-06-02 18:20 UTC, bil-elmoussaoui commented on README.md
>  1- Download the uninstallation file
Can you remove that please? as  there's nothing to download anymore

2017-06-03 15:03 UTC, merged

2017-06-03 15:07 UTC, bil-elmoussaoui commented
I've merged the PR, everything was fine. I was just too tired and i was looking at the other old version of POTFILES. Thanks again for this great PR :+1: